export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const HS_CODE_LIST = [
  { description: "Cotton T-Shirts", hsCode: "6109.10" },
  { description: "Leather Handbags", hsCode: "4202.21" },
  { description: "Mobile Phones", hsCode: "8517.12" },
  { description: "Laptops / Computers", hsCode: "8471.30" },
  { description: "Electronic Components", hsCode: "8542.31" },
  { description: "Jewellery (Gold)", hsCode: "7113.19" },
  { description: "Jewellery (Silver)", hsCode: "7113.11" },
  { description: "Pharmaceuticals / Medicines", hsCode: "3004.90" },
  { description: "Spices", hsCode: "0910.99" },
  { description: "Basmati Rice", hsCode: "1006.30" },
  { description: "Tea", hsCode: "0902.30" },
  { description: "Coffee", hsCode: "0901.11" },
  { description: "Automotive Parts", hsCode: "8708.99" },
  { description: "Bicycle Parts", hsCode: "8714.99" },
  { description: "Surgical Instruments", hsCode: "9018.90" },
  { description: "Ceramic Tiles", hsCode: "6907.21" },
  { description: "Granite / Marble", hsCode: "6802.91" },
  { description: "Cotton Yarn", hsCode: "5205.11" },
  { description: "Silk Fabric", hsCode: "5007.20" },
  { description: "Woolen Garments", hsCode: "6110.11" },
  { description: "Polyester Fabric", hsCode: "5407.61" },
  { description: "Frozen Shrimp", hsCode: "0306.17" },
  { description: "Processed Fish", hsCode: "0305.59" },
  { description: "Mango Pulp", hsCode: "2008.99" },
  { description: "Pickles / Condiments", hsCode: "2001.90" },
  { description: "Essential Oils", hsCode: "3301.29" },
  { description: "Cosmetics / Skincare", hsCode: "3304.99" },
  { description: "Ayurvedic Products", hsCode: "3004.50" },
  { description: "Printed Books", hsCode: "4901.99" },
  { description: "Stationery", hsCode: "4820.10" },
  { description: "Industrial Machinery", hsCode: "8479.89" },
  { description: "Water Pumps", hsCode: "8413.70" },
  { description: "Electric Motors", hsCode: "8501.52" },
  { description: "Solar Panels", hsCode: "8541.40" },
  { description: "LED Lights", hsCode: "9405.42" },
  { description: "Cables and Wires", hsCode: "8544.49" },
  { description: "Steel Pipes", hsCode: "7304.31" },
  { description: "Aluminium Sheets", hsCode: "7606.11" },
  { description: "Plastic Containers", hsCode: "3923.10" },
  { description: "Rubber Products", hsCode: "4016.99" },
  { description: "Wooden Furniture", hsCode: "9403.60" },
  { description: "Handicrafts", hsCode: "9601.90" },
  { description: "Sports Equipment", hsCode: "9506.99" },
  { description: "Toys / Games", hsCode: "9503.00" },
  { description: "Footwear (Leather)", hsCode: "6403.99" },
  { description: "Footwear (Synthetic)", hsCode: "6402.99" },
  { description: "Carpets / Rugs", hsCode: "5703.20" },
  { description: "Home Textiles / Bedsheets", hsCode: "6302.21" },
  { description: "Kitchenware", hsCode: "7323.99" },
  { description: "Watches", hsCode: "9102.11" },
  { description: "Sunglasses", hsCode: "9004.10" },
  { description: "Camera Equipment", hsCode: "9006.53" },
  { description: "Musical Instruments", hsCode: "9207.10" },
  { description: "Art and Paintings", hsCode: "9701.10" },
  { description: "Seeds", hsCode: "1209.99" },
  { description: "Animal Feed", hsCode: "2309.90" },
  { description: "Fertilizers", hsCode: "3102.10" },
  { description: "Pesticides", hsCode: "3808.91" },
  { description: "Chemical Compounds", hsCode: "2942.00" },
  { description: "Paints and Varnishes", hsCode: "3208.90" },
  { description: "Adhesives", hsCode: "3506.91" },
  { description: "Paper and Paperboard", hsCode: "4811.59" },
  { description: "Packaging Material", hsCode: "4819.10" },
  { description: "Garments (Woven)", hsCode: "6211.42" },
  { description: "Denim Jeans", hsCode: "6203.42" },
  { description: "Sarees", hsCode: "5208.39" },
  { description: "Embroidered Fabric", hsCode: "5810.92" },
  { description: "Diamonds (Polished)", hsCode: "7102.39" },
  { description: "Pearls", hsCode: "7101.22" },
  { description: "Gemstones", hsCode: "7103.99" },
  { description: "Imitation Jewellery", hsCode: "7117.19" },
  { description: "Batteries", hsCode: "8507.60" },
  { description: "Chargers / Adapters", hsCode: "8504.40" },
  { description: "Headphones / Earphones", hsCode: "8518.30" },
  { description: "Tablets", hsCode: "8471.30" },
  { description: "Hard Drives", hsCode: "8471.70" },
  { description: "Printed Circuit Boards", hsCode: "8534.00" },
  { description: "Air Conditioners", hsCode: "8415.10" },
  { description: "Refrigerators", hsCode: "8418.10" },
  { description: "Washing Machines", hsCode: "8450.11" },
  { description: "Microwave Ovens", hsCode: "8516.50" },
  { description: "Fans (Electric)", hsCode: "8414.51" },
  { description: "Power Tools", hsCode: "8467.11" },
  { description: "Hand Tools", hsCode: "8205.59" },
  { description: "Valves and Fittings", hsCode: "8481.80" },
  { description: "Bearings", hsCode: "8482.10" },
  { description: "Medical Devices", hsCode: "9018.39" },
  { description: "Diagnostic Equipment", hsCode: "9027.80" },
  { description: "Safety Equipment", hsCode: "9020.00" },
  { description: "Fire Extinguishers", hsCode: "8424.10" },
  { description: "Security Cameras", hsCode: "8525.80" },
  { description: "GPS Devices", hsCode: "8526.91" },
  { description: "Drones", hsCode: "8806.24" },
  { description: "Auto Tyres", hsCode: "4011.10" },
  { description: "Vehicle Batteries", hsCode: "8507.10" },
];

export const MILESTONE_LABELS: Record<string, string> = {
  baggingDone: "Bagging Done",
  customsClearanceAtOrigin: "Customs Clearance at Origin",
  inTransit: "In Transit",
  reachedDestinationPort: "Reached Destination Port",
  movedToWarehouse: "Moved to Warehouse",
  handoverToCarrier: "Handover to Carrier Partner",
  outForDelivery: "Out for Delivery",
};

export const MILESTONE_ORDER = [
  "baggingDone",
  "customsClearanceAtOrigin",
  "inTransit",
  "reachedDestinationPort",
  "movedToWarehouse",
  "handoverToCarrier",
  "outForDelivery",
];

export const CARRIERS = ["UPS", "DHL", "FedEx", "Aramex"];
