export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const HS_CODE_LIST = [
  // Chapter 1-5: Live Animals & Animal Products
  { description: "Live Bovine Animals", hsCode: "0102.29" },
  { description: "Live Poultry (Hens / Chickens)", hsCode: "0105.11" },
  { description: "Fresh / Chilled Beef", hsCode: "0201.30" },
  { description: "Frozen Buffalo Meat", hsCode: "0202.30" },
  { description: "Fresh / Chilled Mutton / Goat Meat", hsCode: "0204.41" },
  { description: "Frozen Chicken", hsCode: "0207.12" },
  { description: "Fresh Fish", hsCode: "0302.89" },
  { description: "Frozen Fish (other)", hsCode: "0303.89" },
  { description: "Dried / Salted Fish", hsCode: "0305.59" },
  { description: "Processed Fish", hsCode: "0305.69" },
  { description: "Crustaceans (Crabs / Lobsters)", hsCode: "0306.14" },
  { description: "Frozen Shrimp / Prawns", hsCode: "0306.17" },
  { description: "Squid / Cuttlefish", hsCode: "0307.43" },
  { description: "Milk (UHT / Packaged)", hsCode: "0401.10" },
  { description: "Butter", hsCode: "0405.10" },
  { description: "Ghee", hsCode: "0405.90" },
  { description: "Cheese", hsCode: "0406.90" },
  { description: "Eggs (Fresh / Hatching)", hsCode: "0407.11" },
  { description: "Honey (Natural)", hsCode: "0409.00" },
  { description: "Silk (Raw)", hsCode: "5002.00" },
  { description: "Wool (Greasy)", hsCode: "5101.11" },

  // Chapter 6-14: Vegetables & Plant Products
  { description: "Fresh Vegetables (General)", hsCode: "0709.99" },
  { description: "Onions (Fresh)", hsCode: "0703.10" },
  { description: "Garlic (Fresh)", hsCode: "0703.20" },
  { description: "Potatoes (Fresh)", hsCode: "0701.90" },
  { description: "Tomatoes (Fresh)", hsCode: "0702.00" },
  { description: "Fresh Ginger", hsCode: "0910.11" },
  { description: "Bananas (Fresh)", hsCode: "0803.90" },
  { description: "Mangoes (Fresh)", hsCode: "0804.50" },
  { description: "Mango Pulp", hsCode: "2008.99" },
  { description: "Grapes (Fresh)", hsCode: "0806.10" },
  { description: "Pomegranates (Fresh)", hsCode: "0810.90" },
  { description: "Coconut (Fresh)", hsCode: "0801.11" },
  { description: "Cashew Nuts (Raw)", hsCode: "0801.31" },
  { description: "Cashew Nuts (Processed / Shelled)", hsCode: "0801.32" },
  { description: "Almonds (Shelled)", hsCode: "0802.12" },
  { description: "Dried Dates", hsCode: "0804.10" },
  { description: "Coffee (Green / Unroasted)", hsCode: "0901.11" },
  { description: "Coffee (Roasted)", hsCode: "0901.21" },
  { description: "Tea (Black)", hsCode: "0902.30" },
  { description: "Tea (Green)", hsCode: "0902.10" },
  { description: "Pepper (Black)", hsCode: "0904.11" },
  { description: "Chilli Pepper (Dried)", hsCode: "0904.21" },
  { description: "Turmeric (Dried)", hsCode: "0910.30" },
  { description: "Cardamom", hsCode: "0908.31" },
  { description: "Cinnamon", hsCode: "0906.11" },
  { description: "Cloves", hsCode: "0907.10" },
  { description: "Nutmeg", hsCode: "0908.11" },
  { description: "Cumin Seeds", hsCode: "0909.21" },
  { description: "Coriander Seeds", hsCode: "0909.10" },
  { description: "Mixed Spices / Masala", hsCode: "0910.91" },
  { description: "Basmati Rice (Milled)", hsCode: "1006.30" },
  { description: "Non-Basmati Rice", hsCode: "1006.40" },
  { description: "Wheat", hsCode: "1001.99" },
  { description: "Wheat Flour (Atta)", hsCode: "1101.00" },
  { description: "Maize / Corn", hsCode: "1005.90" },
  { description: "Soybean", hsCode: "1201.90" },
  { description: "Groundnuts / Peanuts", hsCode: "1202.41" },
  { description: "Sesame Seeds", hsCode: "1207.40" },
  { description: "Sunflower Seeds", hsCode: "1206.00" },
  { description: "Mustard Seeds", hsCode: "1207.50" },
  { description: "Seeds (Other)", hsCode: "1209.99" },
  { description: "Soybean Oil", hsCode: "1507.90" },
  { description: "Groundnut Oil", hsCode: "1508.90" },
  { description: "Coconut Oil", hsCode: "1513.11" },
  { description: "Palm Oil", hsCode: "1511.90" },
  { description: "Castor Oil", hsCode: "1515.30" },
  { description: "Cotton (Raw)", hsCode: "5201.00" },
  { description: "Jute Fibre", hsCode: "5303.10" },

  // Chapter 15-24: Food & Beverages
  { description: "Sugar (White / Refined)", hsCode: "1701.99" },
  { description: "Jaggery (Gur)", hsCode: "1701.14" },
  { description: "Cocoa Powder", hsCode: "1805.00" },
  { description: "Chocolate", hsCode: "1806.90" },
  { description: "Pasta / Noodles", hsCode: "1902.30" },
  { description: "Biscuits / Cookies", hsCode: "1905.31" },
  { description: "Bread / Bakery Products", hsCode: "1905.90" },
  { description: "Pickles / Condiments", hsCode: "2001.90" },
  { description: "Tomato Ketchup / Sauce", hsCode: "2103.20" },
  { description: "Soy Sauce", hsCode: "2103.10" },
  { description: "Curry Powder / Paste", hsCode: "2103.90" },
  { description: "Jam / Jelly / Marmalade", hsCode: "2007.99" },
  { description: "Fruit Juice (Mango)", hsCode: "2009.90" },
  { description: "Fruit Juice (Mixed)", hsCode: "2009.90" },
  { description: "Mineral Water", hsCode: "2201.10" },
  { description: "Soft Drinks / Aerated Water", hsCode: "2202.10" },
  { description: "Fruit Drinks / Nectars", hsCode: "2202.99" },
  { description: "Beer", hsCode: "2203.00" },
  { description: "Whisky", hsCode: "2208.30" },
  { description: "Rum", hsCode: "2208.40" },
  { description: "Tobacco Products / Cigarettes", hsCode: "2402.20" },
  { description: "Animal Feed", hsCode: "2309.90" },

  // Chapter 25-27: Minerals
  { description: "Salt (Industrial / Common)", hsCode: "2501.00" },
  { description: "Limestone", hsCode: "2521.00" },
  { description: "Sand / Silica", hsCode: "2505.10" },
  { description: "Granite (Raw)", hsCode: "2516.11" },
  { description: "Iron Ore", hsCode: "2601.11" },
  { description: "Coal", hsCode: "2701.12" },
  { description: "Petroleum Products / Petrol", hsCode: "2710.12" },
  { description: "Diesel / Fuel Oil", hsCode: "2710.19" },
  { description: "LPG Gas", hsCode: "2711.19" },

  // Chapter 28-38: Chemicals
  { description: "Sulphuric Acid", hsCode: "2807.00" },
  { description: "Caustic Soda (Sodium Hydroxide)", hsCode: "2815.11" },
  { description: "Hydrogen Peroxide", hsCode: "2847.00" },
  { description: "Fertilizers (Urea)", hsCode: "3102.10" },
  { description: "Fertilizers (NPK Compound)", hsCode: "3105.20" },
  { description: "Pesticides / Insecticides", hsCode: "3808.91" },
  { description: "Herbicides", hsCode: "3808.93" },
  { description: "Fungicides", hsCode: "3808.92" },
  { description: "Polymers / Plastics (Raw)", hsCode: "3901.10" },
  { description: "Polyethylene Granules", hsCode: "3901.20" },
  { description: "PVC (Polyvinyl Chloride)", hsCode: "3904.10" },
  { description: "Polypropylene", hsCode: "3902.10" },
  { description: "Paints and Varnishes", hsCode: "3208.90" },
  { description: "Printing Ink", hsCode: "3215.11" },
  { description: "Adhesives / Glue", hsCode: "3506.91" },
  { description: "Soap (Toilet)", hsCode: "3401.11" },
  { description: "Soap (Industrial / Laundry)", hsCode: "3401.20" },
  { description: "Detergent Powder / Liquid", hsCode: "3402.20" },
  { description: "Shampoo", hsCode: "3305.10" },
  { description: "Toothpaste / Oral Hygiene", hsCode: "3306.10" },
  { description: "Deodorants / Antiperspirants", hsCode: "3307.20" },
  { description: "Perfume / Cologne", hsCode: "3303.00" },
  { description: "Cosmetics / Skincare Products", hsCode: "3304.99" },
  { description: "Lipstick / Lip Colour", hsCode: "3304.10" },
  { description: "Eye Makeup / Mascara", hsCode: "3304.20" },
  { description: "Hair Colour / Dye", hsCode: "3305.90" },
  { description: "Essential Oils", hsCode: "3301.29" },
  { description: "Ayurvedic / Herbal Medicines", hsCode: "3004.50" },
  { description: "Pharmaceuticals / Medicines (Tablets)", hsCode: "3004.90" },
  { description: "Antibiotics (Formulated)", hsCode: "3004.20" },
  { description: "Vaccines", hsCode: "3002.20" },
  { description: "Blood / Medical Reagents", hsCode: "3006.40" },
  { description: "Chemical Compounds (Other)", hsCode: "2942.00" },
  { description: "Dyes and Pigments", hsCode: "3204.17" },
  { description: "Printing Chemicals", hsCode: "3707.90" },

  // Chapter 39-40: Plastics & Rubber
  { description: "Plastic Containers / Bottles", hsCode: "3923.10" },
  { description: "Plastic Bags / Sacks", hsCode: "3923.21" },
  { description: "Plastic Pipes and Tubes", hsCode: "3917.21" },
  { description: "Plastic Sheeting / Film", hsCode: "3920.10" },
  { description: "Plastic Housewares", hsCode: "3924.10" },
  { description: "Rubber Products (Other)", hsCode: "4016.99" },
  { description: "Rubber Gloves", hsCode: "4015.12" },
  { description: "Auto Tyres (Cars)", hsCode: "4011.10" },
  { description: "Auto Tyres (Trucks)", hsCode: "4011.20" },
  { description: "Two-Wheeler Tyres", hsCode: "4011.40" },
  { description: "Rubber Hoses", hsCode: "4009.11" },
  { description: "Rubber Gaskets / Seals", hsCode: "4016.93" },

  // Chapter 41-43: Leather
  { description: "Raw Hides and Skins (Bovine)", hsCode: "4101.20" },
  { description: "Tanned Leather (Bovine)", hsCode: "4104.11" },
  { description: "Finished Leather (Crust)", hsCode: "4107.11" },
  { description: "Leather Footwear", hsCode: "6403.99" },
  { description: "Leather Handbags / Purses", hsCode: "4202.21" },
  { description: "Leather Wallets / Pouches", hsCode: "4202.31" },
  { description: "Leather Belts", hsCode: "4205.00" },
  { description: "Leather Gloves", hsCode: "4203.21" },
  { description: "Leather Garments / Jackets", hsCode: "4203.10" },

  // Chapter 44-49: Wood, Paper & Printing
  { description: "Wood (Sawn / Timber)", hsCode: "4407.10" },
  { description: "Plywood", hsCode: "4412.33" },
  { description: "Particle Board / MDF", hsCode: "4410.11" },
  { description: "Wooden Furniture", hsCode: "9403.60" },
  { description: "Wooden Doors / Windows", hsCode: "4418.20" },
  { description: "Wooden Handicrafts / Carvings", hsCode: "4420.10" },
  { description: "Paper and Paperboard", hsCode: "4811.59" },
  { description: "Newsprint", hsCode: "4801.00" },
  { description: "Tissue Paper", hsCode: "4803.00" },
  { description: "Packaging Material (Boxes)", hsCode: "4819.10" },
  { description: "Cartons / Corrugated Board", hsCode: "4819.20" },
  { description: "Printed Books", hsCode: "4901.99" },
  { description: "Newspapers / Periodicals", hsCode: "4902.90" },
  { description: "Stationery (Notebooks / Diaries)", hsCode: "4820.10" },
  { description: "Envelopes / Stationery", hsCode: "4817.10" },

  // Chapter 50-63: Textiles & Garments
  { description: "Silk Yarn", hsCode: "5004.00" },
  { description: "Silk Fabric (Woven)", hsCode: "5007.20" },
  { description: "Sarees (Silk)", hsCode: "5007.90" },
  { description: "Wool Yarn", hsCode: "5106.10" },
  { description: "Woolen Fabric", hsCode: "5112.11" },
  { description: "Woolen Garments / Sweaters", hsCode: "6110.11" },
  { description: "Cotton Yarn (Carded / Combed)", hsCode: "5205.11" },
  { description: "Cotton Fabric (Plain Weave)", hsCode: "5208.11" },
  { description: "Printed Cotton Fabric", hsCode: "5208.39" },
  { description: "Denim Fabric", hsCode: "5209.42" },
  { description: "Polyester Yarn", hsCode: "5402.47" },
  { description: "Polyester Fabric (Woven)", hsCode: "5407.61" },
  { description: "Synthetic Blended Fabric", hsCode: "5516.11" },
  { description: "Knitted Fabric (Cotton)", hsCode: "6006.22" },
  { description: "Embroidered Fabric / Lace", hsCode: "5810.92" },
  { description: "Curtains / Drapes", hsCode: "6303.92" },
  { description: "Home Textiles / Bedsheets", hsCode: "6302.21" },
  { description: "Towels / Terry Cloth", hsCode: "6302.60" },
  { description: "Blankets / Shawls (Wool)", hsCode: "6301.20" },
  { description: "Carpets (Hand-knotted Wool)", hsCode: "5701.10" },
  { description: "Carpets / Rugs (Tufted)", hsCode: "5703.20" },
  { description: "Carpets (Jute / Coir)", hsCode: "5702.49" },
  { description: "Bags (Jute)", hsCode: "6305.10" },
  { description: "T-Shirts / Vests (Cotton Knit)", hsCode: "6109.10" },
  { description: "Shirts (Woven Cotton)", hsCode: "6205.20" },
  { description: "Trousers / Pants (Men, Cotton)", hsCode: "6203.42" },
  { description: "Denim Jeans", hsCode: "6203.42" },
  { description: "Dresses / Skirts (Women)", hsCode: "6204.42" },
  { description: "Sarees (Cotton)", hsCode: "6211.42" },
  { description: "Garments (Woven, Other)", hsCode: "6211.43" },
  { description: "Sportswear / Track Suits", hsCode: "6211.32" },
  { description: "Children Clothing", hsCode: "6209.20" },
  { description: "Undergarments / Innerwear", hsCode: "6207.11" },
  { description: "Hosiery / Socks", hsCode: "6115.95" },
  { description: "Scarves / Stoles (Silk)", hsCode: "6214.10" },
  { description: "Turbans / Headwear", hsCode: "6505.00" },

  // Chapter 64-67: Footwear & Headgear
  { description: "Footwear (Leather Soles)", hsCode: "6403.99" },
  { description: "Footwear (Synthetic / PU)", hsCode: "6402.99" },
  { description: "Footwear (Rubber Soles)", hsCode: "6404.11" },
  { description: "Sports Shoes / Sneakers", hsCode: "6404.11" },
  { description: "Sandals / Chappals (Rubber)", hsCode: "6404.19" },

  // Chapter 68-70: Stone, Ceramics & Glass
  { description: "Granite Slabs / Tiles", hsCode: "6802.23" },
  { description: "Marble Slabs / Tiles", hsCode: "6802.21" },
  { description: "Ceramic Tiles (Floor / Wall)", hsCode: "6907.21" },
  { description: "Vitrified Tiles", hsCode: "6907.22" },
  { description: "Sanitary Ware (Ceramic)", hsCode: "6910.10" },
  { description: "Glass (Float / Sheet)", hsCode: "7005.10" },
  { description: "Glassware (Kitchenware)", hsCode: "7013.49" },
  { description: "Glass Bottles / Jars", hsCode: "7010.90" },

  // Chapter 71: Precious Stones & Metals
  { description: "Diamonds (Rough)", hsCode: "7102.21" },
  { description: "Diamonds (Cut and Polished)", hsCode: "7102.39" },
  { description: "Pearls (Natural)", hsCode: "7101.10" },
  { description: "Cultured Pearls", hsCode: "7101.22" },
  { description: "Emeralds / Precious Gemstones", hsCode: "7103.91" },
  { description: "Semi-Precious Gemstones", hsCode: "7103.99" },
  { description: "Gold (Non-monetary)", hsCode: "7108.12" },
  { description: "Silver (Unwrought)", hsCode: "7106.91" },
  { description: "Platinum", hsCode: "7110.11" },
  { description: "Jewellery (Gold)", hsCode: "7113.19" },
  { description: "Jewellery (Silver)", hsCode: "7113.11" },
  { description: "Imitation Jewellery", hsCode: "7117.19" },

  // Chapter 72-83: Metals
  { description: "Iron and Steel (Bars / Rods)", hsCode: "7213.10" },
  { description: "Steel Sheets / Plates (Hot Rolled)", hsCode: "7208.51" },
  { description: "Stainless Steel (Sheets / Strips)", hsCode: "7219.31" },
  { description: "Steel Pipes and Tubes", hsCode: "7304.31" },
  { description: "Iron / Steel Structures", hsCode: "7308.90" },
  { description: "Copper Wire", hsCode: "7408.11" },
  { description: "Copper Pipes and Tubes", hsCode: "7411.10" },
  { description: "Aluminium Sheets / Plates", hsCode: "7606.11" },
  { description: "Aluminium Profiles / Extrusions", hsCode: "7604.21" },
  { description: "Aluminium Foil", hsCode: "7607.11" },
  { description: "Zinc (Unwrought)", hsCode: "7901.11" },
  { description: "Brass Fittings / Fixtures", hsCode: "7419.99" },
  { description: "Tools (Cutlery / Knives)", hsCode: "8211.92" },
  { description: "Locks and Padlocks", hsCode: "8301.10" },
  { description: "Kitchenware (Steel)", hsCode: "7323.99" },
  { description: "Sanitary Fittings (Taps / Valves)", hsCode: "8481.80" },
  { description: "Nuts / Bolts / Screws (Fasteners)", hsCode: "7318.15" },
  { description: "Springs (Metal)", hsCode: "7320.20" },
  { description: "Chains (Iron / Steel)", hsCode: "7315.11" },

  // Chapter 84-85: Machinery & Electronics
  { description: "Industrial Machinery (General)", hsCode: "8479.89" },
  { description: "Textile Machinery", hsCode: "8445.20" },
  { description: "Packaging Machinery", hsCode: "8422.30" },
  { description: "Food Processing Machinery", hsCode: "8438.80" },
  { description: "Agricultural Machinery (Tractors)", hsCode: "8701.91" },
  { description: "Water Pumps", hsCode: "8413.70" },
  { description: "Air Compressors", hsCode: "8414.80" },
  { description: "Centrifuges", hsCode: "8421.19" },
  { description: "Printing Machinery", hsCode: "8443.39" },
  { description: "CNC Machines / Lathes", hsCode: "8457.10" },
  { description: "Moulds and Dies", hsCode: "8480.71" },
  { description: "Refrigeration Equipment", hsCode: "8418.61" },
  { description: "Air Conditioners (Split)", hsCode: "8415.12" },
  { description: "Washing Machines", hsCode: "8450.11" },
  { description: "Refrigerators", hsCode: "8418.10" },
  { description: "Microwave Ovens", hsCode: "8516.50" },
  { description: "Electric Ovens / Grills", hsCode: "8516.60" },
  { description: "Induction Cooktops", hsCode: "8516.60" },
  { description: "Electric Fans", hsCode: "8414.51" },
  { description: "Vacuum Cleaners", hsCode: "8508.11" },
  { description: "Electric Water Heaters / Geysers", hsCode: "8516.10" },
  { description: "Electric Motors", hsCode: "8501.52" },
  { description: "Generators / Alternators", hsCode: "8502.11" },
  { description: "Transformers", hsCode: "8504.21" },
  { description: "Chargers / Adapters / Power Supplies", hsCode: "8504.40" },
  { description: "Batteries (Lithium-Ion)", hsCode: "8507.60" },
  { description: "Batteries (Lead Acid / Vehicle)", hsCode: "8507.10" },
  { description: "Solar Panels / Photovoltaic Cells", hsCode: "8541.43" },
  { description: "Cables and Wires (Insulated)", hsCode: "8544.49" },
  { description: "Electric Switches / Sockets", hsCode: "8536.50" },
  { description: "Circuit Breakers", hsCode: "8536.20" },
  { description: "LED Lights / Lamps", hsCode: "9405.42" },
  { description: "Fluorescent Lights / CFL", hsCode: "8539.31" },
  { description: "Mobile Phones / Smartphones", hsCode: "8517.13" },
  { description: "Feature Phones / Handsets", hsCode: "8517.12" },
  { description: "Laptops / Notebook Computers", hsCode: "8471.30" },
  { description: "Tablet Computers", hsCode: "8471.30" },
  { description: "Desktop Computers", hsCode: "8471.41" },
  { description: "Computer Servers", hsCode: "8471.49" },
  { description: "Computer Monitors", hsCode: "8528.52" },
  { description: "Printers / Scanners", hsCode: "8443.32" },
  { description: "Hard Disk Drives (HDD)", hsCode: "8471.70" },
  { description: "Solid State Drives (SSD)", hsCode: "8471.70" },
  { description: "Memory Cards / USB Drives", hsCode: "8523.51" },
  { description: "Printed Circuit Boards (PCBs)", hsCode: "8534.00" },
  { description: "Electronic Components (ICs / Chips)", hsCode: "8542.31" },
  { description: "Transistors / Diodes", hsCode: "8541.10" },
  { description: "Resistors / Capacitors", hsCode: "8533.10" },
  { description: "Headphones / Earphones", hsCode: "8518.30" },
  { description: "Speakers / Microphones", hsCode: "8518.22" },
  { description: "Amplifiers / Audio Equipment", hsCode: "8518.40" },
  { description: "Televisions (LED/LCD)", hsCode: "8528.72" },
  { description: "Set Top Boxes / Decoders", hsCode: "8528.71" },
  { description: "CCTV / Security Cameras", hsCode: "8525.80" },
  { description: "Projectors", hsCode: "8528.62" },
  { description: "Routers / Modems / Networking Equipment", hsCode: "8517.62" },
  { description: "GPS Navigation Devices", hsCode: "8526.91" },
  { description: "Power Tools (Electric Drills)", hsCode: "8467.11" },
  { description: "Hand Tools (Spanners / Wrenches)", hsCode: "8205.59" },
  { description: "Bearings (Ball / Roller)", hsCode: "8482.10" },
  { description: "Valves (Industrial)", hsCode: "8481.20" },

  // Chapter 86-89: Vehicles & Transport
  { description: "Passenger Cars", hsCode: "8703.23" },
  { description: "Commercial Vehicles / Trucks", hsCode: "8704.21" },
  { description: "Two-Wheelers (Motorcycles)", hsCode: "8711.20" },
  { description: "Auto Parts / Spare Parts", hsCode: "8708.99" },
  { description: "Vehicle Engines", hsCode: "8407.34" },
  { description: "Gearboxes / Transmissions", hsCode: "8708.40" },
  { description: "Automotive Brakes / Parts", hsCode: "8708.30" },
  { description: "Bicycle Parts / Accessories", hsCode: "8714.99" },
  { description: "Ships / Boats", hsCode: "8901.90" },
  { description: "Aircraft Parts", hsCode: "8803.30" },

  // Chapter 90-92: Precision Instruments
  { description: "Medical Devices (General)", hsCode: "9018.39" },
  { description: "Surgical Instruments", hsCode: "9018.90" },
  { description: "Dental Equipment / Instruments", hsCode: "9018.49" },
  { description: "Diagnostic Equipment (Lab)", hsCode: "9027.80" },
  { description: "X-Ray Equipment", hsCode: "9022.14" },
  { description: "Thermometers", hsCode: "9025.11" },
  { description: "Blood Pressure Monitors", hsCode: "9018.19" },
  { description: "Optical Lenses / Spectacles", hsCode: "9004.90" },
  { description: "Sunglasses", hsCode: "9004.10" },
  { description: "Microscopes", hsCode: "9011.10" },
  { description: "Telescopes / Binoculars", hsCode: "9005.10" },
  { description: "Cameras (DSLR / Digital)", hsCode: "9006.53" },
  { description: "Camera Lenses", hsCode: "9002.11" },
  { description: "Watches (Wrist)", hsCode: "9102.11" },
  { description: "Clocks", hsCode: "9105.91" },
  { description: "Flow Meters / Measuring Instruments", hsCode: "9026.10" },
  { description: "Safety Equipment (Respirators)", hsCode: "9020.00" },
  { description: "Fire Extinguishers", hsCode: "8424.10" },
  { description: "Musical Instruments (Keyboards)", hsCode: "9207.10" },
  { description: "Guitars / String Instruments", hsCode: "9202.90" },
  { description: "Tabla / Percussion Instruments", hsCode: "9206.00" },

  // Chapter 93-97: Miscellaneous
  { description: "Sports Equipment / Goods", hsCode: "9506.99" },
  { description: "Toys (Plastic / Electronic)", hsCode: "9503.00" },
  { description: "Board Games / Playing Cards", hsCode: "9504.40" },
  { description: "Art / Paintings / Drawings", hsCode: "9701.10" },
  { description: "Antiques (Over 100 Years)", hsCode: "9706.00" },
  { description: "Stamps / Coins (Collectibles)", hsCode: "9704.00" },
  { description: "Drones / Unmanned Aircraft", hsCode: "8806.24" },
  { description: "Pens / Writing Instruments", hsCode: "9608.10" },
  { description: "Pencils", hsCode: "9609.10" },
  { description: "Brushes (Paint / Art)", hsCode: "9603.40" },
  { description: "Umbrellas", hsCode: "6601.91" },
  { description: "Buttons / Zippers / Fasteners (Garment)", hsCode: "9606.21" },

  // Handicrafts & Indian Specialty Items
  { description: "Handicrafts (Stone / Marble)", hsCode: "6802.99" },
  { description: "Handicrafts (Wood Carvings)", hsCode: "4420.10" },
  { description: "Handicrafts (Brass / Metal)", hsCode: "8306.29" },
  { description: "Handicrafts (Ceramic / Terracotta)", hsCode: "6913.90" },
  { description: "Handicrafts (Textile / Embroidery)", hsCode: "6217.10" },
  { description: "Handicrafts (Leather)", hsCode: "4205.00" },
  { description: "Handicrafts (Bamboo / Cane)", hsCode: "4602.12" },
  { description: "Incense Sticks / Agarbatti", hsCode: "3307.49" },
  { description: "Pooja / Religious Articles", hsCode: "9706.00" },
];

export const MILESTONE_LABELS: Record<string, string> = {
  baggingDone: "Bagging Done",
  customsClearanceAtOrigin: "Customs Clearance at Origin",
  inTransit: "In Transit",
  reachedDestinationPort: "Reached Destination Port",
  movedToWarehouse: "Moved to Warehouse",
  handoverToCarrier: "Handover to Carrier Partner",
  outForDelivery: "Out for Delivery",
};

export const MILESTONE_ORDER = [
  "baggingDone",
  "customsClearanceAtOrigin",
  "inTransit",
  "reachedDestinationPort",
  "movedToWarehouse",
  "handoverToCarrier",
  "outForDelivery",
];

export const CARRIERS = ["UPS", "DHL", "FedEx", "Aramex"];
