/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AWBNumber = IDL.Text;
export const TrackingMilestone = IDL.Variant({
  'outForDelivery' : IDL.Null,
  'handoverToCarrier' : IDL.Null,
  'movedToWarehouse' : IDL.Null,
  'inTransit' : IDL.Null,
  'reachedDestinationPort' : IDL.Null,
  'baggingDone' : IDL.Null,
  'customsClearanceAtOrigin' : IDL.Null,
});
export const FranchiseId = IDL.Text;
export const Franchise = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'isActive' : IDL.Bool,
  'contactEmail' : IDL.Text,
  'franchiseName' : IDL.Text,
  'franchiseId' : FranchiseId,
  'contactPhone' : IDL.Text,
});
export const BookingId = IDL.Nat;
export const AWBAssignRequest = IDL.Record({
  'bookingId' : BookingId,
  'awbNumber' : IDL.Text,
});
export const KycType = IDL.Variant({
  'pan' : IDL.Null,
  'passport' : IDL.Null,
  'aadhaar' : IDL.Null,
  'drivingLicense' : IDL.Null,
});
export const Shipper = IDL.Record({
  'kycNumber' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'kycType' : KycType,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const BoxItem = IDL.Record({
  'total' : IDL.Float64,
  'rate' : IDL.Float64,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'boxNumber' : IDL.Nat,
  'hsCode' : IDL.Text,
});
export const Invoice = IDL.Record({
  'invoiceDate' : Time,
  'invoiceNumber' : IDL.Text,
  'currency' : IDL.Text,
});
export const UserId = IDL.Text;
export const Box = IDL.Record({
  'height' : IDL.Float64,
  'grossWeight' : IDL.Float64,
  'length' : IDL.Float64,
  'volumeWeight' : IDL.Float64,
  'width' : IDL.Float64,
  'boxNumber' : IDL.Nat,
});
export const Consignee = IDL.Record({
  'name' : IDL.Text,
  'idNumber' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'idType' : KycType,
});
export const Booking = IDL.Record({
  'shipper' : Shipper,
  'status' : BookingStatus,
  'bookingId' : BookingId,
  'awbAssignedDate' : IDL.Opt(Time),
  'boxItems' : IDL.Vec(BoxItem),
  'invoice' : Invoice,
  'awbNumber' : IDL.Opt(AWBNumber),
  'createdBy' : UserId,
  'createdTimestamp' : Time,
  'boxes' : IDL.Vec(Box),
  'updatedTimestamp' : Time,
  'originCountry' : IDL.Text,
  'destinationCountry' : IDL.Text,
  'consignee' : Consignee,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BillingItem = IDL.Record({
  'rate' : IDL.Float64,
  'gstPercent' : IDL.Float64,
  'description' : IDL.Text,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const BillingRecordId = IDL.Text;
export const BillingRecord = IDL.Record({
  'id' : BillingRecordId,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  }),
  'customerGstin' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'taxableAmount' : IDL.Float64,
  'cgst' : IDL.Float64,
  'discountAmount' : IDL.Float64,
  'igst' : IDL.Float64,
  'createdAt' : Time,
  'sgst' : IDL.Float64,
  'billDate' : Time,
  'billType' : IDL.Variant({ 'gst' : IDL.Null, 'nonGst' : IDL.Null }),
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'billNumber' : IDL.Text,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(BillingItem),
  'taxType' : IDL.Variant({
    'igst' : IDL.Null,
    'none' : IDL.Null,
    'cgstSgst' : IDL.Null,
  }),
  'subtotal' : IDL.Float64,
});
export const CustomerId = IDL.Text;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductId = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'gstPercent' : IDL.Float64,
  'isActive' : IDL.Bool,
  'price' : IDL.Float64,
  'hsnSacCode' : IDL.Text,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'notes' : IDL.Text,
  'paymentDate' : Time,
  'amount' : IDL.Float64,
  'billingRecordId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'franchiseId' : IDL.Opt(FranchiseId),
});
export const TrackingUpdate = IDL.Record({
  'awbNumber' : AWBNumber,
  'carrierTrackingURL' : IDL.Opt(IDL.Text),
  'carrierName' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'milestone' : TrackingMilestone,
  'carrierTrackingNumber' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrackingUpdate' : IDL.Func(
      [
        AWBNumber,
        TrackingMilestone,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'adminResetFranchisePassword' : IDL.Func(
      [FranchiseId, IDL.Text],
      [Franchise],
      [],
    ),
  'assignAWBAndApprove' : IDL.Func([AWBAssignRequest], [Booking], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBillingRecord' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Variant({ 'gst' : IDL.Null, 'nonGst' : IDL.Null }),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(BillingItem),
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Variant({
          'igst' : IDL.Null,
          'none' : IDL.Null,
          'cgstSgst' : IDL.Null,
        }),
        IDL.Text,
        IDL.Variant({
          'paid' : IDL.Null,
          'unpaid' : IDL.Null,
          'partial' : IDL.Null,
        }),
        IDL.Text,
      ],
      [BillingRecord],
      [],
    ),
  'createBooking' : IDL.Func(
      [Shipper, Consignee, IDL.Text, Invoice, IDL.Vec(Box), IDL.Vec(BoxItem)],
      [Booking],
      [],
    ),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
  'createFranchise' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Franchise],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
  'deleteBillingRecord' : IDL.Func([BillingRecordId], [], []),
  'deleteCustomer' : IDL.Func([CustomerId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'franchiseeUpdatePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllFranchisees' : IDL.Func([], [IDL.Vec(Franchise)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getBillingRecordById' : IDL.Func(
      [BillingRecordId],
      [BillingRecord],
      ['query'],
    ),
  'getBillingRecords' : IDL.Func([], [IDL.Vec(BillingRecord)], ['query']),
  'getBookingByAWB' : IDL.Func([AWBNumber], [Booking], ['query']),
  'getBookingById' : IDL.Func([BookingId], [Booking], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getFranchise' : IDL.Func([FranchiseId], [Franchise], ['query']),
  'getPaymentsForBill' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getTrackingByAWB' : IDL.Func(
      [AWBNumber],
      [IDL.Vec(TrackingUpdate)],
      ['query'],
    ),
  'getTrackingByBookingId' : IDL.Func(
      [BookingId],
      [IDL.Vec(TrackingUpdate)],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationsRead' : IDL.Func([], [], []),
  'recordPayment' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, Time, IDL.Text],
      [PaymentRecord],
      [],
    ),
  'rejectBooking' : IDL.Func([BookingId], [Booking], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'test' : IDL.Func([], [], []),
  'updateBillingRecord' : IDL.Func(
      [
        BillingRecordId,
        IDL.Text,
        Time,
        IDL.Variant({ 'gst' : IDL.Null, 'nonGst' : IDL.Null }),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(BillingItem),
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Variant({
          'igst' : IDL.Null,
          'none' : IDL.Null,
          'cgstSgst' : IDL.Null,
        }),
        IDL.Text,
        IDL.Variant({
          'paid' : IDL.Null,
          'unpaid' : IDL.Null,
          'partial' : IDL.Null,
        }),
        IDL.Text,
      ],
      [BillingRecord],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [CustomerId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
  'updateFranchise' : IDL.Func(
      [FranchiseId, IDL.Text, IDL.Text, IDL.Text],
      [Franchise],
      [],
    ),
  'updateFranchiseStatus' : IDL.Func([FranchiseId, IDL.Bool], [Franchise], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AWBNumber = IDL.Text;
  const TrackingMilestone = IDL.Variant({
    'outForDelivery' : IDL.Null,
    'handoverToCarrier' : IDL.Null,
    'movedToWarehouse' : IDL.Null,
    'inTransit' : IDL.Null,
    'reachedDestinationPort' : IDL.Null,
    'baggingDone' : IDL.Null,
    'customsClearanceAtOrigin' : IDL.Null,
  });
  const FranchiseId = IDL.Text;
  const Franchise = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'isActive' : IDL.Bool,
    'contactEmail' : IDL.Text,
    'franchiseName' : IDL.Text,
    'franchiseId' : FranchiseId,
    'contactPhone' : IDL.Text,
  });
  const BookingId = IDL.Nat;
  const AWBAssignRequest = IDL.Record({
    'bookingId' : BookingId,
    'awbNumber' : IDL.Text,
  });
  const KycType = IDL.Variant({
    'pan' : IDL.Null,
    'passport' : IDL.Null,
    'aadhaar' : IDL.Null,
    'drivingLicense' : IDL.Null,
  });
  const Shipper = IDL.Record({
    'kycNumber' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'kycType' : KycType,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const BoxItem = IDL.Record({
    'total' : IDL.Float64,
    'rate' : IDL.Float64,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'boxNumber' : IDL.Nat,
    'hsCode' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'invoiceDate' : Time,
    'invoiceNumber' : IDL.Text,
    'currency' : IDL.Text,
  });
  const UserId = IDL.Text;
  const Box = IDL.Record({
    'height' : IDL.Float64,
    'grossWeight' : IDL.Float64,
    'length' : IDL.Float64,
    'volumeWeight' : IDL.Float64,
    'width' : IDL.Float64,
    'boxNumber' : IDL.Nat,
  });
  const Consignee = IDL.Record({
    'name' : IDL.Text,
    'idNumber' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'idType' : KycType,
  });
  const Booking = IDL.Record({
    'shipper' : Shipper,
    'status' : BookingStatus,
    'bookingId' : BookingId,
    'awbAssignedDate' : IDL.Opt(Time),
    'boxItems' : IDL.Vec(BoxItem),
    'invoice' : Invoice,
    'awbNumber' : IDL.Opt(AWBNumber),
    'createdBy' : UserId,
    'createdTimestamp' : Time,
    'boxes' : IDL.Vec(Box),
    'updatedTimestamp' : Time,
    'originCountry' : IDL.Text,
    'destinationCountry' : IDL.Text,
    'consignee' : Consignee,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BillingItem = IDL.Record({
    'rate' : IDL.Float64,
    'gstPercent' : IDL.Float64,
    'description' : IDL.Text,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const BillingRecordId = IDL.Text;
  const BillingRecord = IDL.Record({
    'id' : BillingRecordId,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'paid' : IDL.Null,
      'unpaid' : IDL.Null,
      'partial' : IDL.Null,
    }),
    'customerGstin' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'taxableAmount' : IDL.Float64,
    'cgst' : IDL.Float64,
    'discountAmount' : IDL.Float64,
    'igst' : IDL.Float64,
    'createdAt' : Time,
    'sgst' : IDL.Float64,
    'billDate' : Time,
    'billType' : IDL.Variant({ 'gst' : IDL.Null, 'nonGst' : IDL.Null }),
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'billNumber' : IDL.Text,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(BillingItem),
    'taxType' : IDL.Variant({
      'igst' : IDL.Null,
      'none' : IDL.Null,
      'cgstSgst' : IDL.Null,
    }),
    'subtotal' : IDL.Float64,
  });
  const CustomerId = IDL.Text;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductId = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'gstPercent' : IDL.Float64,
    'isActive' : IDL.Bool,
    'price' : IDL.Float64,
    'hsnSacCode' : IDL.Text,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'notes' : IDL.Text,
    'paymentDate' : Time,
    'amount' : IDL.Float64,
    'billingRecordId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'franchiseId' : IDL.Opt(FranchiseId),
  });
  const TrackingUpdate = IDL.Record({
    'awbNumber' : AWBNumber,
    'carrierTrackingURL' : IDL.Opt(IDL.Text),
    'carrierName' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'milestone' : TrackingMilestone,
    'carrierTrackingNumber' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrackingUpdate' : IDL.Func(
        [
          AWBNumber,
          TrackingMilestone,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'adminResetFranchisePassword' : IDL.Func(
        [FranchiseId, IDL.Text],
        [Franchise],
        [],
      ),
    'assignAWBAndApprove' : IDL.Func([AWBAssignRequest], [Booking], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBillingRecord' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Variant({ 'gst' : IDL.Null, 'nonGst' : IDL.Null }),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(BillingItem),
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Variant({
            'igst' : IDL.Null,
            'none' : IDL.Null,
            'cgstSgst' : IDL.Null,
          }),
          IDL.Text,
          IDL.Variant({
            'paid' : IDL.Null,
            'unpaid' : IDL.Null,
            'partial' : IDL.Null,
          }),
          IDL.Text,
        ],
        [BillingRecord],
        [],
      ),
    'createBooking' : IDL.Func(
        [Shipper, Consignee, IDL.Text, Invoice, IDL.Vec(Box), IDL.Vec(BoxItem)],
        [Booking],
        [],
      ),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
    'createFranchise' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Franchise],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
    'deleteBillingRecord' : IDL.Func([BillingRecordId], [], []),
    'deleteCustomer' : IDL.Func([CustomerId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'franchiseeUpdatePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllFranchisees' : IDL.Func([], [IDL.Vec(Franchise)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getBillingRecordById' : IDL.Func(
        [BillingRecordId],
        [BillingRecord],
        ['query'],
      ),
    'getBillingRecords' : IDL.Func([], [IDL.Vec(BillingRecord)], ['query']),
    'getBookingByAWB' : IDL.Func([AWBNumber], [Booking], ['query']),
    'getBookingById' : IDL.Func([BookingId], [Booking], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getFranchise' : IDL.Func([FranchiseId], [Franchise], ['query']),
    'getPaymentsForBill' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getTrackingByAWB' : IDL.Func(
        [AWBNumber],
        [IDL.Vec(TrackingUpdate)],
        ['query'],
      ),
    'getTrackingByBookingId' : IDL.Func(
        [BookingId],
        [IDL.Vec(TrackingUpdate)],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationsRead' : IDL.Func([], [], []),
    'recordPayment' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, Time, IDL.Text],
        [PaymentRecord],
        [],
      ),
    'rejectBooking' : IDL.Func([BookingId], [Booking], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'test' : IDL.Func([], [], []),
    'updateBillingRecord' : IDL.Func(
        [
          BillingRecordId,
          IDL.Text,
          Time,
          IDL.Variant({ 'gst' : IDL.Null, 'nonGst' : IDL.Null }),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(BillingItem),
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Variant({
            'igst' : IDL.Null,
            'none' : IDL.Null,
            'cgstSgst' : IDL.Null,
          }),
          IDL.Text,
          IDL.Variant({
            'paid' : IDL.Null,
            'unpaid' : IDL.Null,
            'partial' : IDL.Null,
          }),
          IDL.Text,
        ],
        [BillingRecord],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [CustomerId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
    'updateFranchise' : IDL.Func(
        [FranchiseId, IDL.Text, IDL.Text, IDL.Text],
        [Franchise],
        [],
      ),
    'updateFranchiseStatus' : IDL.Func(
        [FranchiseId, IDL.Bool],
        [Franchise],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };