/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AWBAssignRequest {
  'bookingId' : BookingId,
  'awbNumber' : string,
}
export type AWBNumber = string;
export interface Booking {
  'shipper' : Shipper,
  'status' : BookingStatus,
  'bookingId' : BookingId,
  'awbAssignedDate' : [] | [Time],
  'boxItems' : Array<BoxItem>,
  'invoice' : Invoice,
  'awbNumber' : [] | [AWBNumber],
  'createdBy' : UserId,
  'createdTimestamp' : Time,
  'boxes' : Array<Box>,
  'updatedTimestamp' : Time,
  'originCountry' : string,
  'destinationCountry' : string,
  'consignee' : Consignee,
}
export type BookingId = bigint;
export type BookingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Box {
  'height' : number,
  'grossWeight' : number,
  'length' : number,
  'volumeWeight' : number,
  'width' : number,
  'boxNumber' : bigint,
}
export interface BoxItem {
  'total' : number,
  'rate' : number,
  'description' : string,
  'quantity' : bigint,
  'boxNumber' : bigint,
  'hsCode' : string,
}
export interface Consignee {
  'name' : string,
  'idNumber' : string,
  'address' : string,
  'phone' : string,
  'idType' : KycType,
}
export interface Franchise {
  'principal' : Principal,
  'username' : string,
  'isActive' : boolean,
  'contactEmail' : string,
  'franchiseName' : string,
  'franchiseId' : FranchiseId,
  'contactPhone' : string,
}
export type FranchiseId = string;
export interface Invoice {
  'invoiceDate' : Time,
  'invoiceNumber' : string,
  'currency' : string,
}
export type KycType = { 'pan' : null } |
  { 'passport' : null } |
  { 'aadhaar' : null } |
  { 'drivingLicense' : null };
export interface Shipper {
  'kycNumber' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
  'kycType' : KycType,
}
export type Time = bigint;
export type TrackingMilestone = { 'outForDelivery' : null } |
  { 'handoverToCarrier' : null } |
  { 'movedToWarehouse' : null } |
  { 'inTransit' : null } |
  { 'reachedDestinationPort' : null } |
  { 'baggingDone' : null } |
  { 'customsClearanceAtOrigin' : null };
export interface TrackingUpdate {
  'awbNumber' : AWBNumber,
  'carrierTrackingURL' : [] | [string],
  'carrierName' : [] | [string],
  'notes' : [] | [string],
  'timestamp' : Time,
  'milestone' : TrackingMilestone,
  'carrierTrackingNumber' : [] | [string],
}
export type UserId = string;
export interface UserProfile {
  'userId' : string,
  'name' : string,
  'role' : UserRole,
  'franchiseId' : [] | [FranchiseId],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrackingUpdate' : ActorMethod<
    [
      AWBNumber,
      TrackingMilestone,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'adminResetFranchisePassword' : ActorMethod<[FranchiseId, string], Franchise>,
  'assignAWBAndApprove' : ActorMethod<[AWBAssignRequest], Booking>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [Shipper, Consignee, string, Invoice, Array<Box>, Array<BoxItem>],
    Booking
  >,
  'createFranchise' : ActorMethod<
    [Principal, string, string, string, string],
    Franchise
  >,
  'franchiseeUpdatePassword' : ActorMethod<[string, string], undefined>,
  'getAllFranchisees' : ActorMethod<[], Array<Franchise>>,
  'getBookingByAWB' : ActorMethod<[AWBNumber], Booking>,
  'getBookingById' : ActorMethod<[BookingId], Booking>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFranchise' : ActorMethod<[FranchiseId], Franchise>,
  'getTrackingByAWB' : ActorMethod<[AWBNumber], Array<TrackingUpdate>>,
  'getTrackingByBookingId' : ActorMethod<[BookingId], Array<TrackingUpdate>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'rejectBooking' : ActorMethod<[BookingId], Booking>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'test' : ActorMethod<[], undefined>,
  'updateFranchise' : ActorMethod<
    [FranchiseId, string, string, string],
    Franchise
  >,
  'updateFranchiseStatus' : ActorMethod<[FranchiseId, boolean], Franchise>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];