/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AWBNumber = IDL.Text;
export const TrackingMilestone = IDL.Variant({
  'outForDelivery' : IDL.Null,
  'handoverToCarrier' : IDL.Null,
  'movedToWarehouse' : IDL.Null,
  'inTransit' : IDL.Null,
  'reachedDestinationPort' : IDL.Null,
  'baggingDone' : IDL.Null,
  'customsClearanceAtOrigin' : IDL.Null,
});
export const FranchiseId = IDL.Text;
export const Franchise = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'isActive' : IDL.Bool,
  'contactEmail' : IDL.Text,
  'franchiseName' : IDL.Text,
  'franchiseId' : FranchiseId,
  'contactPhone' : IDL.Text,
});
export const BookingId = IDL.Nat;
export const AWBAssignRequest = IDL.Record({
  'bookingId' : BookingId,
  'awbNumber' : IDL.Text,
});
export const KycType = IDL.Variant({
  'pan' : IDL.Null,
  'passport' : IDL.Null,
  'aadhaar' : IDL.Null,
  'drivingLicense' : IDL.Null,
});
export const Shipper = IDL.Record({
  'kycNumber' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'kycType' : KycType,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const BoxItem = IDL.Record({
  'total' : IDL.Float64,
  'rate' : IDL.Float64,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'boxNumber' : IDL.Nat,
  'hsCode' : IDL.Text,
});
export const Invoice = IDL.Record({
  'invoiceDate' : Time,
  'invoiceNumber' : IDL.Text,
  'currency' : IDL.Text,
});
export const UserId = IDL.Text;
export const Box = IDL.Record({
  'height' : IDL.Float64,
  'grossWeight' : IDL.Float64,
  'length' : IDL.Float64,
  'volumeWeight' : IDL.Float64,
  'width' : IDL.Float64,
  'boxNumber' : IDL.Nat,
});
export const Consignee = IDL.Record({
  'name' : IDL.Text,
  'idNumber' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'idType' : KycType,
});
export const Booking = IDL.Record({
  'shipper' : Shipper,
  'status' : BookingStatus,
  'bookingId' : BookingId,
  'awbAssignedDate' : IDL.Opt(Time),
  'boxItems' : IDL.Vec(BoxItem),
  'invoice' : Invoice,
  'awbNumber' : IDL.Opt(AWBNumber),
  'createdBy' : UserId,
  'createdTimestamp' : Time,
  'boxes' : IDL.Vec(Box),
  'updatedTimestamp' : Time,
  'originCountry' : IDL.Text,
  'destinationCountry' : IDL.Text,
  'consignee' : Consignee,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'franchiseId' : IDL.Opt(FranchiseId),
});
export const TrackingUpdate = IDL.Record({
  'awbNumber' : AWBNumber,
  'carrierTrackingURL' : IDL.Opt(IDL.Text),
  'carrierName' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'milestone' : TrackingMilestone,
  'carrierTrackingNumber' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrackingUpdate' : IDL.Func(
      [
        AWBNumber,
        TrackingMilestone,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'adminResetFranchisePassword' : IDL.Func(
      [FranchiseId, IDL.Text],
      [Franchise],
      [],
    ),
  'assignAWBAndApprove' : IDL.Func([AWBAssignRequest], [Booking], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [Shipper, Consignee, IDL.Text, Invoice, IDL.Vec(Box), IDL.Vec(BoxItem)],
      [Booking],
      [],
    ),
  'createFranchise' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Franchise],
      [],
    ),
  'franchiseeUpdatePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllFranchisees' : IDL.Func([], [IDL.Vec(Franchise)], ['query']),
  'getBookingByAWB' : IDL.Func([AWBNumber], [Booking], ['query']),
  'getBookingById' : IDL.Func([BookingId], [Booking], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFranchise' : IDL.Func([FranchiseId], [Franchise], ['query']),
  'getTrackingByAWB' : IDL.Func(
      [AWBNumber],
      [IDL.Vec(TrackingUpdate)],
      ['query'],
    ),
  'getTrackingByBookingId' : IDL.Func(
      [BookingId],
      [IDL.Vec(TrackingUpdate)],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationsRead' : IDL.Func([], [], []),
  'rejectBooking' : IDL.Func([BookingId], [Booking], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'test' : IDL.Func([], [], []),
  'updateFranchise' : IDL.Func(
      [FranchiseId, IDL.Text, IDL.Text, IDL.Text],
      [Franchise],
      [],
    ),
  'updateFranchiseStatus' : IDL.Func([FranchiseId, IDL.Bool], [Franchise], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AWBNumber = IDL.Text;
  const TrackingMilestone = IDL.Variant({
    'outForDelivery' : IDL.Null,
    'handoverToCarrier' : IDL.Null,
    'movedToWarehouse' : IDL.Null,
    'inTransit' : IDL.Null,
    'reachedDestinationPort' : IDL.Null,
    'baggingDone' : IDL.Null,
    'customsClearanceAtOrigin' : IDL.Null,
  });
  const FranchiseId = IDL.Text;
  const Franchise = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'isActive' : IDL.Bool,
    'contactEmail' : IDL.Text,
    'franchiseName' : IDL.Text,
    'franchiseId' : FranchiseId,
    'contactPhone' : IDL.Text,
  });
  const BookingId = IDL.Nat;
  const AWBAssignRequest = IDL.Record({
    'bookingId' : BookingId,
    'awbNumber' : IDL.Text,
  });
  const KycType = IDL.Variant({
    'pan' : IDL.Null,
    'passport' : IDL.Null,
    'aadhaar' : IDL.Null,
    'drivingLicense' : IDL.Null,
  });
  const Shipper = IDL.Record({
    'kycNumber' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'kycType' : KycType,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const BoxItem = IDL.Record({
    'total' : IDL.Float64,
    'rate' : IDL.Float64,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'boxNumber' : IDL.Nat,
    'hsCode' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'invoiceDate' : Time,
    'invoiceNumber' : IDL.Text,
    'currency' : IDL.Text,
  });
  const UserId = IDL.Text;
  const Box = IDL.Record({
    'height' : IDL.Float64,
    'grossWeight' : IDL.Float64,
    'length' : IDL.Float64,
    'volumeWeight' : IDL.Float64,
    'width' : IDL.Float64,
    'boxNumber' : IDL.Nat,
  });
  const Consignee = IDL.Record({
    'name' : IDL.Text,
    'idNumber' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'idType' : KycType,
  });
  const Booking = IDL.Record({
    'shipper' : Shipper,
    'status' : BookingStatus,
    'bookingId' : BookingId,
    'awbAssignedDate' : IDL.Opt(Time),
    'boxItems' : IDL.Vec(BoxItem),
    'invoice' : Invoice,
    'awbNumber' : IDL.Opt(AWBNumber),
    'createdBy' : UserId,
    'createdTimestamp' : Time,
    'boxes' : IDL.Vec(Box),
    'updatedTimestamp' : Time,
    'originCountry' : IDL.Text,
    'destinationCountry' : IDL.Text,
    'consignee' : Consignee,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'franchiseId' : IDL.Opt(FranchiseId),
  });
  const TrackingUpdate = IDL.Record({
    'awbNumber' : AWBNumber,
    'carrierTrackingURL' : IDL.Opt(IDL.Text),
    'carrierName' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'milestone' : TrackingMilestone,
    'carrierTrackingNumber' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrackingUpdate' : IDL.Func(
        [
          AWBNumber,
          TrackingMilestone,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'adminResetFranchisePassword' : IDL.Func(
        [FranchiseId, IDL.Text],
        [Franchise],
        [],
      ),
    'assignAWBAndApprove' : IDL.Func([AWBAssignRequest], [Booking], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [Shipper, Consignee, IDL.Text, Invoice, IDL.Vec(Box), IDL.Vec(BoxItem)],
        [Booking],
        [],
      ),
    'createFranchise' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Franchise],
        [],
      ),
    'franchiseeUpdatePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllFranchisees' : IDL.Func([], [IDL.Vec(Franchise)], ['query']),
    'getBookingByAWB' : IDL.Func([AWBNumber], [Booking], ['query']),
    'getBookingById' : IDL.Func([BookingId], [Booking], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFranchise' : IDL.Func([FranchiseId], [Franchise], ['query']),
    'getTrackingByAWB' : IDL.Func(
        [AWBNumber],
        [IDL.Vec(TrackingUpdate)],
        ['query'],
      ),
    'getTrackingByBookingId' : IDL.Func(
        [BookingId],
        [IDL.Vec(TrackingUpdate)],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationsRead' : IDL.Func([], [], []),
    'rejectBooking' : IDL.Func([BookingId], [Booking], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'test' : IDL.Func([], [], []),
    'updateFranchise' : IDL.Func(
        [FranchiseId, IDL.Text, IDL.Text, IDL.Text],
        [Franchise],
        [],
      ),
    'updateFranchiseStatus' : IDL.Func(
        [FranchiseId, IDL.Bool],
        [Franchise],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };