/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = bigint;
export type Time = bigint;
export interface Box {
    height: number;
    grossWeight: number;
    length: number;
    volumeWeight: number;
    width: number;
    boxNumber: bigint;
}
export type FranchiseId = string;
export interface Invoice {
    invoiceDate: Time;
    invoiceNumber: string;
    currency: string;
}
export type AWBNumber = string;
export type UserId = string;
export interface AWBAssignRequest {
    bookingId: BookingId;
    awbNumber: string;
}
export interface TrackingUpdate {
    awbNumber: AWBNumber;
    carrierTrackingURL?: string;
    carrierName?: string;
    notes?: string;
    timestamp: Time;
    milestone: TrackingMilestone;
    carrierTrackingNumber?: string;
}
export interface BoxItem {
    total: number;
    rate: number;
    description: string;
    quantity: bigint;
    boxNumber: bigint;
    hsCode: string;
}
export interface Booking {
    shipper: Shipper;
    status: BookingStatus;
    bookingId: BookingId;
    awbAssignedDate?: Time;
    boxItems: Array<BoxItem>;
    invoice: Invoice;
    awbNumber?: AWBNumber;
    createdBy: UserId;
    createdTimestamp: Time;
    boxes: Array<Box>;
    updatedTimestamp: Time;
    originCountry: string;
    destinationCountry: string;
    consignee: Consignee;
}
export interface Shipper {
    kycNumber: string;
    name: string;
    address: string;
    phone: string;
    kycType: KycType;
}
export interface Franchise {
    principal: Principal;
    username: string;
    isActive: boolean;
    contactEmail: string;
    franchiseName: string;
    franchiseId: FranchiseId;
    contactPhone: string;
}
export interface UserProfile {
    userId: string;
    name: string;
    role: UserRole;
    franchiseId?: FranchiseId;
}
export interface Consignee {
    name: string;
    idNumber: string;
    address: string;
    phone: string;
    idType: KycType;
}
export enum BookingStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum KycType {
    pan = "pan",
    passport = "passport",
    aadhaar = "aadhaar",
    drivingLicense = "drivingLicense"
}
export enum TrackingMilestone {
    outForDelivery = "outForDelivery",
    handoverToCarrier = "handoverToCarrier",
    movedToWarehouse = "movedToWarehouse",
    inTransit = "inTransit",
    reachedDestinationPort = "reachedDestinationPort",
    baggingDone = "baggingDone",
    customsClearanceAtOrigin = "customsClearanceAtOrigin"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTrackingUpdate(awbNumber: AWBNumber, milestone: TrackingMilestone, notes: string | null, carrierName: string | null, carrierTrackingNumber: string | null, carrierTrackingURL: string | null): Promise<void>;
    adminResetFranchisePassword(franchiseId: FranchiseId, newPassword: string): Promise<Franchise>;
    assignAWBAndApprove(awbAssignRequest: AWBAssignRequest): Promise<Booking>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(shipper: Shipper, consignee: Consignee, destinationCountry: string, invoice: Invoice, boxes: Array<Box>, boxItems: Array<BoxItem>): Promise<Booking>;
    createFranchise(franchisePrincipal: Principal, username: string, franchiseName: string, contactPhone: string, contactEmail: string): Promise<Franchise>;
    franchiseeUpdatePassword(currentPassword: string, newPassword: string): Promise<void>;
    getAllFranchisees(): Promise<Array<Franchise>>;
    getBookingByAWB(awbNumber: AWBNumber): Promise<Booking>;
    getBookingById(bookingId: BookingId): Promise<Booking>;
    getBookings(): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFranchise(franchiseId: FranchiseId): Promise<Franchise>;
    getTrackingByAWB(awbNumber: AWBNumber): Promise<Array<TrackingUpdate>>;
    getTrackingByBookingId(bookingId: BookingId): Promise<Array<TrackingUpdate>>;
    getUnreadCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationsRead(): Promise<void>;
    rejectBooking(bookingId: BookingId): Promise<Booking>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    test(): Promise<void>;
    updateFranchise(franchiseId: FranchiseId, franchiseName: string, contactPhone: string, contactEmail: string): Promise<Franchise>;
    updateFranchiseStatus(franchiseId: FranchiseId, isActive: boolean): Promise<Franchise>;
}
import type { AWBNumber as _AWBNumber, Booking as _Booking, BookingId as _BookingId, BookingStatus as _BookingStatus, Box as _Box, BoxItem as _BoxItem, Consignee as _Consignee, FranchiseId as _FranchiseId, Invoice as _Invoice, KycType as _KycType, Shipper as _Shipper, Time as _Time, TrackingMilestone as _TrackingMilestone, TrackingUpdate as _TrackingUpdate, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTrackingUpdate(arg0: AWBNumber, arg1: TrackingMilestone, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrackingUpdate(arg0, to_candid_TrackingMilestone_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrackingUpdate(arg0, to_candid_TrackingMilestone_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async adminResetFranchisePassword(arg0: FranchiseId, arg1: string): Promise<Franchise> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetFranchisePassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetFranchisePassword(arg0, arg1);
            return result;
        }
    }
    async assignAWBAndApprove(arg0: AWBAssignRequest): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAWBAndApprove(arg0);
                return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAWBAndApprove(arg0);
            return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: Shipper, arg1: Consignee, arg2: string, arg3: Invoice, arg4: Array<Box>, arg5: Array<BoxItem>): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_Shipper_n18(this._uploadFile, this._downloadFile, arg0), to_candid_Consignee_n22(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_Shipper_n18(this._uploadFile, this._downloadFile, arg0), to_candid_Consignee_n22(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFranchise(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Franchise> {
        if (this.processError) {
            try {
                const result = await this.actor.createFranchise(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFranchise(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async franchiseeUpdatePassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.franchiseeUpdatePassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.franchiseeUpdatePassword(arg0, arg1);
            return result;
        }
    }
    async getAllFranchisees(): Promise<Array<Franchise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFranchisees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFranchisees();
            return result;
        }
    }
    async getBookingByAWB(arg0: AWBNumber): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingByAWB(arg0);
                return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingByAWB(arg0);
            return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: BookingId): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFranchise(arg0: FranchiseId): Promise<Franchise> {
        if (this.processError) {
            try {
                const result = await this.actor.getFranchise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFranchise(arg0);
            return result;
        }
    }
    async getTrackingByAWB(arg0: AWBNumber): Promise<Array<TrackingUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackingByAWB(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackingByAWB(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrackingByBookingId(arg0: BookingId): Promise<Array<TrackingUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackingByBookingId(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackingByBookingId(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async rejectBooking(arg0: BookingId): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBooking(arg0);
                return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBooking(arg0);
            return from_candid_Booking_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async test(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.test();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.test();
            return result;
        }
    }
    async updateFranchise(arg0: FranchiseId, arg1: string, arg2: string, arg3: string): Promise<Franchise> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFranchise(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFranchise(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateFranchiseStatus(arg0: FranchiseId, arg1: boolean): Promise<Franchise> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFranchiseStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFranchiseStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Consignee_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Consignee): Consignee {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_KycType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycType): KycType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Shipper_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shipper): Shipper {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_TrackingMilestone_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackingMilestone): TrackingMilestone {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_TrackingUpdate_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackingUpdate): TrackingUpdate {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AWBNumber]): AWBNumber | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FranchiseId]): FranchiseId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    idNumber: string;
    address: string;
    phone: string;
    idType: _KycType;
}): {
    name: string;
    idNumber: string;
    address: string;
    phone: string;
    idType: KycType;
} {
    return {
        name: value.name,
        idNumber: value.idNumber,
        address: value.address,
        phone: value.phone,
        idType: from_candid_KycType_n8(_uploadFile, _downloadFile, value.idType)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: string;
    name: string;
    role: _UserRole;
    franchiseId: [] | [_FranchiseId];
}): {
    userId: string;
    name: string;
    role: UserRole;
    franchiseId?: FranchiseId;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: from_candid_UserRole_n28(_uploadFile, _downloadFile, value.role),
        franchiseId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.franchiseId))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    awbNumber: _AWBNumber;
    carrierTrackingURL: [] | [string];
    carrierName: [] | [string];
    notes: [] | [string];
    timestamp: _Time;
    milestone: _TrackingMilestone;
    carrierTrackingNumber: [] | [string];
}): {
    awbNumber: AWBNumber;
    carrierTrackingURL?: string;
    carrierName?: string;
    notes?: string;
    timestamp: Time;
    milestone: TrackingMilestone;
    carrierTrackingNumber?: string;
} {
    return {
        awbNumber: value.awbNumber,
        carrierTrackingURL: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.carrierTrackingURL)),
        carrierName: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.carrierName)),
        notes: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        milestone: from_candid_TrackingMilestone_n35(_uploadFile, _downloadFile, value.milestone),
        carrierTrackingNumber: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.carrierTrackingNumber))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipper: _Shipper;
    status: _BookingStatus;
    bookingId: _BookingId;
    awbAssignedDate: [] | [_Time];
    boxItems: Array<_BoxItem>;
    invoice: _Invoice;
    awbNumber: [] | [_AWBNumber];
    createdBy: _UserId;
    createdTimestamp: _Time;
    boxes: Array<_Box>;
    updatedTimestamp: _Time;
    originCountry: string;
    destinationCountry: string;
    consignee: _Consignee;
}): {
    shipper: Shipper;
    status: BookingStatus;
    bookingId: BookingId;
    awbAssignedDate?: Time;
    boxItems: Array<BoxItem>;
    invoice: Invoice;
    awbNumber?: AWBNumber;
    createdBy: UserId;
    createdTimestamp: Time;
    boxes: Array<Box>;
    updatedTimestamp: Time;
    originCountry: string;
    destinationCountry: string;
    consignee: Consignee;
} {
    return {
        shipper: from_candid_Shipper_n6(_uploadFile, _downloadFile, value.shipper),
        status: from_candid_BookingStatus_n10(_uploadFile, _downloadFile, value.status),
        bookingId: value.bookingId,
        awbAssignedDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.awbAssignedDate)),
        boxItems: value.boxItems,
        invoice: value.invoice,
        awbNumber: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.awbNumber)),
        createdBy: value.createdBy,
        createdTimestamp: value.createdTimestamp,
        boxes: value.boxes,
        updatedTimestamp: value.updatedTimestamp,
        originCountry: value.originCountry,
        destinationCountry: value.destinationCountry,
        consignee: from_candid_Consignee_n14(_uploadFile, _downloadFile, value.consignee)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kycNumber: string;
    name: string;
    address: string;
    phone: string;
    kycType: _KycType;
}): {
    kycNumber: string;
    name: string;
    address: string;
    phone: string;
    kycType: KycType;
} {
    return {
        kycNumber: value.kycNumber,
        name: value.name,
        address: value.address,
        phone: value.phone,
        kycType: from_candid_KycType_n8(_uploadFile, _downloadFile, value.kycType)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): BookingStatus {
    return "pending" in value ? BookingStatus.pending : "approved" in value ? BookingStatus.approved : "rejected" in value ? BookingStatus.rejected : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outForDelivery: null;
} | {
    handoverToCarrier: null;
} | {
    movedToWarehouse: null;
} | {
    inTransit: null;
} | {
    reachedDestinationPort: null;
} | {
    baggingDone: null;
} | {
    customsClearanceAtOrigin: null;
}): TrackingMilestone {
    return "outForDelivery" in value ? TrackingMilestone.outForDelivery : "handoverToCarrier" in value ? TrackingMilestone.handoverToCarrier : "movedToWarehouse" in value ? TrackingMilestone.movedToWarehouse : "inTransit" in value ? TrackingMilestone.inTransit : "reachedDestinationPort" in value ? TrackingMilestone.reachedDestinationPort : "baggingDone" in value ? TrackingMilestone.baggingDone : "customsClearanceAtOrigin" in value ? TrackingMilestone.customsClearanceAtOrigin : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pan: null;
} | {
    passport: null;
} | {
    aadhaar: null;
} | {
    drivingLicense: null;
}): KycType {
    return "pan" in value ? KycType.pan : "passport" in value ? KycType.passport : "aadhaar" in value ? KycType.aadhaar : "drivingLicense" in value ? KycType.drivingLicense : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrackingUpdate>): Array<TrackingUpdate> {
    return value.map((x)=>from_candid_TrackingUpdate_n32(_uploadFile, _downloadFile, x));
}
function to_candid_Consignee_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Consignee): _Consignee {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_KycType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycType): _KycType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Shipper_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shipper): _Shipper {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_TrackingMilestone_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrackingMilestone): _TrackingMilestone {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kycNumber: string;
    name: string;
    address: string;
    phone: string;
    kycType: KycType;
}): {
    kycNumber: string;
    name: string;
    address: string;
    phone: string;
    kycType: _KycType;
} {
    return {
        kycNumber: value.kycNumber,
        name: value.name,
        address: value.address,
        phone: value.phone,
        kycType: to_candid_KycType_n20(_uploadFile, _downloadFile, value.kycType)
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    idNumber: string;
    address: string;
    phone: string;
    idType: KycType;
}): {
    name: string;
    idNumber: string;
    address: string;
    phone: string;
    idType: _KycType;
} {
    return {
        name: value.name,
        idNumber: value.idNumber,
        address: value.address,
        phone: value.phone,
        idType: to_candid_KycType_n20(_uploadFile, _downloadFile, value.idType)
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: string;
    name: string;
    role: UserRole;
    franchiseId?: FranchiseId;
}): {
    userId: string;
    name: string;
    role: _UserRole;
    franchiseId: [] | [_FranchiseId];
} {
    return {
        userId: value.userId,
        name: value.name,
        role: to_candid_UserRole_n16(_uploadFile, _downloadFile, value.role),
        franchiseId: value.franchiseId ? candid_some(value.franchiseId) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrackingMilestone): {
    outForDelivery: null;
} | {
    handoverToCarrier: null;
} | {
    movedToWarehouse: null;
} | {
    inTransit: null;
} | {
    reachedDestinationPort: null;
} | {
    baggingDone: null;
} | {
    customsClearanceAtOrigin: null;
} {
    return value == TrackingMilestone.outForDelivery ? {
        outForDelivery: null
    } : value == TrackingMilestone.handoverToCarrier ? {
        handoverToCarrier: null
    } : value == TrackingMilestone.movedToWarehouse ? {
        movedToWarehouse: null
    } : value == TrackingMilestone.inTransit ? {
        inTransit: null
    } : value == TrackingMilestone.reachedDestinationPort ? {
        reachedDestinationPort: null
    } : value == TrackingMilestone.baggingDone ? {
        baggingDone: null
    } : value == TrackingMilestone.customsClearanceAtOrigin ? {
        customsClearanceAtOrigin: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycType): {
    pan: null;
} | {
    passport: null;
} | {
    aadhaar: null;
} | {
    drivingLicense: null;
} {
    return value == KycType.pan ? {
        pan: null
    } : value == KycType.passport ? {
        passport: null
    } : value == KycType.aadhaar ? {
        aadhaar: null
    } : value == KycType.drivingLicense ? {
        drivingLicense: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
